### ISSUE TITLE
2 of 3 install methods didn't pull the data

### ISSUE THREAD

**Issue by vmbb** [karan/joe#16]
homebrew installed joe, but "joe ls" had no output

pip install installed joe, bu "joe ls" had no output

the git method worked fine!

**Comment by jrhoads** [comment]
Confirmed.
also worked around this by pip installing then doing a
git clone https://github.com/github/gitignore.git data
from within the env/lib/python2.7/site-packages/joe
This works

An admitted  hack, not a solution, but it confirms the problem with the data directory

**Comment by vmbb** [comment]
Thank you sir. The project was listed in the ImportPython newsletter today, so you may get a small surge of folks grabbing the project.
- Brian

On Jan 15, 2015, at 14:06, Joseph Rhoads <notifications@github.com<mailto:notifications@github.com>> wrote:

Confirmed.
also worked around this by pip installing then doing a
git clone https://github.com/github/gitignore.githttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_github_gitignore.git&d=AwMCaQ&c=Sqcl0Ez6M0X8aeM67LKIiDJAXVeAw-YihVMNtXt-uEs&r=4mz7U9ZSQ4eAecnuE1iTE424Pvvtu6meCDXaE7eG_Qw&m=jAYoL_eZ1PVLccqwsTDVelMCbxYdePUn8SMbDjiTETs&s=o-pK5gks8ZYxeG8SjR9M9LsYTQSY0dk599-5BwnoiTg&e= data
from within the env/lib/python2.7/site-packages/joe
This works

An admitted hack, not a solution, but it confirms the problem with the data directory

**Comment by karan** [comment]
This fixed pip.

Fixing homebrew is harder, github doesn't include submodules in releases. Trying to figure that out.

**Comment by vmbb** [comment]
To be honest, I was a bit surprised to see the homebrew install, but I liked it, since I use the tool on my mac ;)
- Brian

On Jan 15, 2015, at 15:51, Karan Goel <notifications@github.com<mailto:notifications@github.com>> wrote:

This fixed pip.

Fixing homebrew is harder, github doesn't include submodules in releases. Trying to figure that out.

**Comment by karan** [comment]
All fixed. @vmbb, @jrhoads 

```
brew update
brew install gitignore
```

This is what I see:

![image](https://cloud.githubusercontent.com/assets/3261985/5768703/37d9260a-9cc8-11e4-97a4-073a9cc0694b.png)

**Comment by karan** [comment]
Also, yay we got into a newsletter. :tada:
