### ISSUE TITLE
Makefile instead of `tool.sh`?

### ISSUE THREAD

**Issue by syndbg** [karan/joe#27]
A makefile's purpose perfectly fits replacing `tool.sh`.

While `tool.sh` gets the job done, it is not the most convenient way.
From a programmer's point-of-view, we need to write the command parsing logic ourselves.
But from a user's - `./tool.sh something` isn't more convenient than `make something`.

Of course, this is just nitpicking at the details. It isn't a real issue or anything.

**Comment by karan** [comment]
Will look into it.

I was also looking at tox (with `tox.ini` file) and it looks ideal for python projects. Any experience with that?

**Comment by syndbg** [comment]
I do. But unless we introduce tests and requirements, we don't need to create multiple virtual envs (using tox).
