### ISSUE TITLE
joe update

### ISSUE THREAD

**Issue by KangOl** [karan/joe#28]
Why vendoring https://github.com/github/gitignore?

Why not adding a `joe update` command that will do a `git pull --quiet --force` of the gitignore repository?
The initial clone can be done automatically at first call

And why not allowing to update from another repository (with custom gitignore files (see #9))

**Comment by karan** [comment]
Looking into it.

**Comment by karan** [comment]
We might want to do what's being proposed in #9. For any platform, we make a `~/.joe` folder where all gitignore files can reside.

Post installation, we run `joe update` which pulls in the submodules and structures the folder as:

```
- .joe
---- github/gitignore  # submodule
--------- Global 
---- custom   # custom files can go in here
```

**Comment by KangOl** [comment]
This is not a submodule but a simple git repository.

Personally, I would follow [XDG specs](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) and store data in `~/.local/share/joe`

**Comment by mcandre** [comment]
+1 Great idea!

**Comment by CodeMan99** [comment]
You could use the [Github API](https://developer.github.com/v3/gitignore/) so that you don't need to worry this at all. The API automatically pulls the latest version from the [gitignore repo](https://github.com/github/gitignore). I suppose using the API would conflict with using [gitignore.io](http://gitignore.io).

**Comment by AndrewSB** [comment]
+1

**Comment by sobolevn** [comment]
+1. For now `joe` is not synced with [python-ignore](https://github.com/github/gitignore/blob/master/Python.gitignore). Notice the `.eggs` folder.

After running `pip install --upgrade joe`, now I am using `joe 0.0.6`. Still missing some patterns.
