### ISSUE TITLE
Ping a server and show update notice if there's a new version

### ISSUE THREAD

**Issue by karan** [karan/joe#32]
I like how npm does it.

When the user runs the command, ping some server, and if there's a newer version, show a banner for updating `joe`.

**Comment by Ubadub** [comment]
Hey karan,

I'm looking to get into contributing to open source. I was wondering if I could tackle this issue? I'm just wondering what server I should ping.

Let me know what you think.

Thanks,
Ubadub

**Comment by karan** [comment]
@Ubadub, Thanks for wanting to helps. We would need to write a simple HTTP server. I think it would be best if I did this issue, since it isn't a priority right now.

**Comment by gamerlv** [comment]
For this issues you don't even need your own HTTP server. All one has to do is check if there is an higher version number available in the json returned by https://api.github.com/repos/karan/joe/tags. Using the `name` attribute as version number of course.
