### ISSUE TITLE
Repeatable creation of the demo gif animation

### ISSUE THREAD

**Issue by joelpurra** [karan/joe#33]
Developed a brand new tool [shell-keystroke-animator](https://github.com/joelpurra/shell-keystroke-animator) for creating GIF animations for shell programs, code snippets and more. Here's a recreated version of the `joe` demo. Admittedly, it doesn't recreate mouse movements/selections. Instead I used `view`, which highlights comments, and scrolled through the longer `.gitignore` by glitching some noop-commands.

Good news is that it's super easy to iterate over the animation creation, so please fix it the way you please.

Input:

``` text
joe
joe ls
joe java
joe java > .gitignore
cat .gitignore
joe java python osx > .gitignore
view .gitignore
zzzzzzzzLzzzzzzzzzzzzzzzzLzzzzzzzzzzzzzzzzLzzL
```

Output:

![joe](https://cloud.githubusercontent.com/assets/1398544/5881423/047bd17a-a341-11e4-86cd-e8f818369431.gif)

**Comment by sheharyarn** [comment]
:+1:

**Comment by karan** [comment]
Is there a way to set the width and height of the terminal? I would love to add this to the README if it had a shorter height.

**Comment by joelpurra** [comment]
@karan: you set the window size yourself before starting the recording. See window size examples on https://github.com/joelpurra/shell-keystroke-animator

**Comment by karan** [comment]
Bug?

![output](https://cloud.githubusercontent.com/assets/3261985/6093202/44f8e956-aeb1-11e4-84ad-e0b8bb3617f9.gif)

**Comment by joelpurra** [comment]
@karan: no - guess you didn't switch to the "other" window, which is where the recording happens.

**Comment by karan** [comment]
Ah.

Not the animate part is stuck for some reason. Probably because there's way too many files?, and `read` takes a looong time.

**Comment by joelpurra** [comment]
@karan: you mean creating the gif from all the png files, or something else? Sure, that takes a while sometimes -- depending on the speed of your computer of course.

What do you mean by `read`? Did you set a custom `keysleep` maybe?

**Comment by karan** [comment]
I mean the `read` command used in your source code. I didn't set `keysleep`.

I think I waiter for ~5 minutes.

Oh well, I'll close this issue for now since it isn't actually an issue and start one in your repo.

**Comment by joelpurra** [comment]
@karan: alright, that would work too. Can only confirm that it's working on my machine (as can be seen in the animation in the first post) so feedback would be great!
