### ISSUE TITLE
The URL in the .gitignore is no longer valid and has a cert issue.

### ISSUE THREAD

**Issue by dontrebootme** [karan/joe#34]
I don't want all the people that see the awesome gitignores to think joe is bad because the advertised link in the gitignore doesnt work. :smile:

**Comment by karan** [comment]
What do you mean? It works just fine for me. Closing for now.

**Comment by dontrebootme** [comment]
Still seeing cert issues:
http://i.imgur.com/CLJd5O4.png

**Comment by karan** [comment]
Fixed https://github.com/karan/joe/commit/742172b2612e28539c18fa2213732c7fbc0c6216
