### ISSUE TITLE
Python 3 support: Version 0.0.5

### ISSUE THREAD

**Issue by geekpradd** [karan/joe#42]
The problem appears to be solved in Version 0.0.6 but the <a href="https://pypi.python.org/pypi/joe">PyPi</a> version is still 0.0.5. The main problem is the lack of parenthesis surrounding `print` statements which are a necessity for Python 3 as print is a function in Python 3.

Using `from __future__ import print_function` should work and all `print` statements must be replaced with `print()`

![a](https://cloud.githubusercontent.com/assets/7867775/6480662/1e7f78e2-c27c-11e4-95f1-6f551f183d41.PNG)

**Comment by geekpradd** [comment]
@karan, This issue can be very easily solved by just pushing Version 0.0.6 to PyPI. Most Linux and Windows users of joe are using PyPI so I suggest you to push the changes as soon as possible.

It shouldn't take much time should it?

**Comment by karan** [comment]
Done. I've been busy with school, blogging and other commitments. Thanks for being patient.
