### ISSUE TITLE
joe doesn't list any "types"

### ISSUE THREAD

**Issue by rpural** [karan/joe#44]
rpMacPro:~ rpn$ joe ls

rpMacPro:~ rpn$

After source install. Tried to list the types of files joe would build the .gitignore for, and the list is empty. What have I missed?

**Comment by rpural** [comment]
Also tried the following:

rpMacPro:~ rpn$ joe java
joe doesn't know the following gitignores:
java
Run `joe ls` to see list of available gitignores.
[]
rpMacPro:~ rpn$

**Comment by karan** [comment]
OS? Version of `joe`? How did you install it?
