### ISSUE TITLE
gitignore.io

### ISSUE THREAD

**Issue by andreis** [karan/joe#53]
Just thought I'd mention [gitignore.io](https://www.gitignore.io/) in case you don't know about it. You can for example compare how the gitignore snippets compare with yours.

I'm a long-time user of it; I love the fact that I can curl and pipe that stuff easily. It's also neat to have the command with the full path a simple Ctrl+R away in `zsh`.

Kudos for your work, and for making joe installable via `brew`.

**Comment by sheharyarn** [comment]
:+1:

**Comment by pgrosslicht** [comment]
The .gitignores generated with joe and with https://gitignore.io should be the same, they both use the .gitignores from https://github.com/github/gitignore

Only thing is that joe's status of that repository is already 9 months old, while gitignore.io's is one month old.

**Comment by hairesis** [comment]
There is also a [plugin for oh my zsh](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gitignore) which uses gitignore.io

**Comment by karan** [comment]
:)
