### ISSUE TITLE
'joe ls' is now outputting incorrect and incomplete information

### ISSUE THREAD

**Issue by munrocape** [karan/joe#7]
Now that data/ is under version control, the output of `joe ls` includes the .git file and neglects all of the .gitignore files within data/Global.

``` bash
$ joe ls
.git, actionscript, ada, agda, android, appceleratortitanium, archlinuxpackages, autotools, c++, c, cakephp, cfwheels, chefcookbook, clojure, cmake, codeigniter, commonlisp, composer, concrete5, contributing.md, coq, craftcms, dart, delphi, dm, drupal, eagle, elisp, elixir, episerver, erlang, expressionengine, extjs, fancy, finale, forcedotcom, fortran, fuelphp, gcov, gitbook, go, gradle, grails, gwt, haskell, idris, igorpro, java, jboss, jekyll, joomla, jython, kohana, labview, laravel, leiningen, lemonstand, license, lilypond, lithium, lua, magento, maven, mercury, metaprogrammingsystem, meteor, nanoc, nim, node, objective-c, ocaml, opa, opencart, oracleforms, packer, perl, phalcon, playframework, plone, prestashop, processing, python, qooxdoo, qt, r, rails, readme.md, rhodesrhomobile, ros, ruby, rust, sass, scala, scons, scrivener, sdcc, seamgen, sketchup, stella, sugarcrm, swift, symfony, symphonycms, tex, textpattern, turbogears2, typo3, umbraco, unity, visualstudio, vvvv, waf, wordpress, xojo, yeoman, yii, zendframework, zephir
```

**Comment by munrocape** [comment]
PR forthcoming

**Comment by csu** [comment]
Prior to the switch to using git submodule, it didn't include the files within Global: https://github.com/karan/joe/tree/4e359896fdeee4168ca0ba522881f2eb055a7ddb/joe/data (try to search for Eclipse or one of the other files in Global). I was about mention it. They can be easily added by just checking another folder for files.

**Comment by karan** [comment]
Yeah I didn't include `Global` on purpose to keep it simple, and have enough time to think about how to structure the directory. Starting #9 to discuss this more.

@munrocape will wait for your PR. Thanks for taking this on.
