### ISSUE TITLE
Generate not working for 1.0.1

### ISSUE THREAD

**Issue by hayorov** [karan/joe#78]
Show heal instead of generated gitignore file.
Installed as binary from https://github.com/karan/joe/releases/tag/1.0.1

mbp:fallball-spa allexx$ joe --version

 ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
 ▀▀▀▀▀█░█▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀▀▀
      ▐░▌    ▐░▌       ▐░▌▐░▌
      ▐░▌    ▐░▌       ▐░▌▐░█▄▄▄▄▄▄▄▄▄
      ▐░▌    ▐░▌       ▐░▌▐░░░░░░░░░░░▌
      ▐░▌    ▐░▌       ▐░▌▐░█▀▀▀▀▀▀▀▀▀
      ▐░▌    ▐░▌       ▐░▌▐░▌
 ▄▄▄▄▄█░▌    ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄▄▄
▐░░░░░░░▌    ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
 ▀▀▀▀▀▀▀      ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀
 version 1.0.0

mbp:fallball-spa allexx$ joe u
Updating gitignore files..

mbp:fallball-spa allexx$ joe g vim windows sublimetext osx node jetbrains
NAME:

 ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
 ▀▀▀▀▀█░█▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀▀▀
      ▐░▌    ▐░▌       ▐░▌▐░▌
      ▐░▌    ▐░▌       ▐░▌▐░█▄▄▄▄▄▄▄▄▄
      ▐░▌    ▐░▌       ▐░▌▐░░░░░░░░░░░▌
      ▐░▌    ▐░▌       ▐░▌▐░█▀▀▀▀▀▀▀▀▀
      ▐░▌    ▐░▌       ▐░▌▐░▌
 ▄▄▄▄▄█░▌    ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄▄▄
▐░░░░░░░▌    ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
 ▀▀▀▀▀▀▀      ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀
- generate .gitignore files from the command line

USAGE:
   joe command [arguments...]

VERSION:
   1.0.0

COMMANDS:
    ls  list all available files
    u   update all available gitignore files
    g   generate gitignore files

GLOBAL OPTIONS:
   --help, -h       show help
   --version, -v    print the version

Also shows version 1.0.0 expected 1.0.1

**Comment by karan** [comment]
`joe u` updates the gitignore files not joe itself. Please download the new binary and replace existing one with that.
