### ISSUE TITLE
brew install error

### ISSUE THREAD

**Issue by notice501** [karan/joe#8]
Error: undefined method `homepage' for Gitignore:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Taps/karan/homebrew-karan/Formula/gitignore.rb:2:in`class:Gitignore'
/usr/local/Library/Taps/karan/homebrew-karan/Formula/gitignore.rb:1:in `<main>'

**Comment by karan** [comment]
Try running `brew update` and then installing.

**Comment by karan** [comment]
@notice501 assuming it worked. can you confirm, please?

**Comment by notice501** [comment]
@karan Yes,it worked for me,thanks.

**Comment by karan** [comment]
Great!
