### ISSUE TITLE
bash: ./joe: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by chandanpasunoori** [karan/joe#85]
bash: ./joe: cannot execute binary file: Exec format error

**Comment by Nairwolf** [comment]
Hi @karan, I have the same error than @etsrepo. 

I'm using a Linux OS (Xubuntu). This binary is supposed to work on linux platform ? I know I could be able to compile `joe` from sources, but I don't want to install Go environment just for this software, sorry.

**Comment by chandanpasunoori** [comment]
I'm also using Ubuntu only. but still not working, do I need to configure anything.?

**Comment by decached** [comment]
Same problem. I guess the binary has been built for some other operating system.

`go get github.com/karan/joe/` works fine, so I guess this has nothing to do with the code.

**Comment by karan** [comment]
New binaries are out. https://github.com/karan/joe/releases/tag/1.0.2
